---
Resources:
  #My security Group
  MySecurityGroupSSH:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH access in port 22
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22
  #Definicion de la instancia ec2
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: "ami-a4c7edb2"
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref MySecurityGroupSSH
  #Definicion ip elastica
  MyElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref MyEC2Instance